name: Deploy CI
on:
  push:
    branches: [file-system]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Yarn
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to Vercel Action
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_PAT }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          alias-domains: |
            teslo-shop-api-alexander-lancellott.vercel.app
            {{BRANCH}}-tsa.alexander-lancellott.vercel.app
